export default {
    HELP: 1,
    ECHO: 2,
    TOKEN: 3,
    
    BALANCE: 4,
    BALANCE_CHANGE: 5,
    BALANCE_CATEGORY_CHANGE: 6,
    BALANCE_COMMENT_CHANGE: 7,
    BALANCE_REMOVE: 8,
    BALANCE_REPORT: 9,
    BALANCE_STATS: 10
}