export default {
    ERROR: -1,
    START: 0,
    HELP: 1,
    ECHO: 2,
    TOKEN: 3,
    BALANCE: 4,
    BALANCE_INIT: 5,
    BALANCE_CHANGE: 6,
    BALANCE_CATEGORY_CHANGE: 7,
    BALANCE_COMMENT_CHANGE: 8,
    BALANCE_REMOVE: 9,
    BALANCE_REPORT: 10,
    BALANCE_STATS: 11
}
